name: Python Lint

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
  pull_request:
    branches: 
      - main
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install pylint
    - name: Install package dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Lint main with pylint
      run: |
        pylint *.py
    - name: Lint ocsf with pylint
      run: |
        pylint ocsf
    - name: Lint fdr with pylint
      run: |
        pylint fdr
