name: Spell Check
on:
  pull_request:
    paths:
    - '**.md'
  push:
    paths:
    - '**.md'
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Spelling
      uses: SFLScientific/spellcheck-github-actions@master
